### ISSUE TITLE
[Suggestions] navbar

### ISSUE THREAD

**Issue by SilverLlama** [Token07/phpbb3-serversboard#1]
Hey,

I don't know if you're still actively developing this but I have a suggestion. I think it would be nice in the navbar instead of having the little page icon to refer to the page is would say "X players online..." and when you click it, it would take you to the page. the X would stand for the total amount of people online at that moment.

**Comment by Token07** [comment]
Great idea.
I'm still working on it, but I haven't had a lot of time to recently.
