### ISSUE TITLE
Arma 3 (Armed Assault 3) Not Working

### ISSUE THREAD

**Issue by OmenLW** [Token07/phpbb3-serversboard#2]
This game server (Arma 3) does not display any information. I am using the correct port (game port +1) and nothing is being displayed. 

I am also having this issue with TeamSpeak 3.

Ark: Survival Evolved is displaying properly.

**Comment by Token07** [comment]
I know for sure Teamspeak requires changing some permissions, so that probably why Teamspeak isn't working for you.
